version: '3.8'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "secapp@2022"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/data
    restart: always

  log-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "secapp@2022" 
      Database: "SECURITYAPP_DB"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mssql-server
    restart: always
    volumes:
      - ./app:/app

volumes:
  mssql-data:
    driver: local