USE LOG_DB
GO

CREATE TABLE [dbo].[LOG_INTEGRATION_TYPE]  
(     
	[ID_LOG_INTEGRATION_TYPE] INT NOT NULL, 
	[NM_LOG_INTEGRATION_TYPE] VARCHAR(255) NULL, 
	[IS_ACTIVE] BIT NULL, 
	CONSTRAINT [PK_LOG_INTEGRATION_TYPE] PRIMARY KEY ([ID_LOG_INTEGRATION_TYPE] ASC)
);

ALTER TABLE [dbo].[LOG_INTEGRATION_TYPE] ADD CONSTRAINT [DF_LIT_IS_ACTIVE] DEFAULT ((1)) FOR IS_ACTIVE;
