USE LOG_DB
GO

CREATE TABLE [dbo].[LOG_INTEGRATION]  
(     
	[ID_LOG_INTEGRATION] BIGINT PRIMARY KEY NOT NULL IDENTITY(1,1), 
	[ID_PROJECT] BIGINT NULL, 
	[ID_MAILING] BIGINT NULL, 
	[ID_LOG_INTEGRATION_TYPE] INT NOT NULL, 
	[DT_CREATION] DATETIME NULL, 
	[DT_LAST_UPDATE] DATETIME NULL, 
	[NU_VERSION] VARCHAR(50) NULL, 
	[DE_METHOD] VARCHAR(50) NULL, 
	[DE_URL] VARCHAR(255) NULL, 
	[DE_CONTENT] VARCHAR(MAX) NULL, 
	[DE_RESULT] VARCHAR(MAX) NULL, 
	[DE_MESSAGE] VARCHAR(255) NULL, 
	[DE_EXCEPTION_MESSAGE] VARCHAR(MAX) NULL, 
	[DE_STACK_TRACE] VARCHAR(MAX) NULL, 
	[IS_SUCCESS] BIT NULL, 
	[IS_TEST] BIT NULL,
	[IS_ACTIVE] BIT NULL
);